# Generated by Django 5.2.12 on 2026-03-10 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('artist', models.CharField(blank=True, max_length=200, verbose_name='Исполнитель')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('audio_file', models.FileField(upload_to='media/tracks/', verbose_name='Аудиофайл')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='media/covers/', verbose_name='Обложка')),
                ('plays_count', models.IntegerField(default=0, verbose_name='Прослушивания')),
                ('genre', models.CharField(blank=True, choices=[('фигня', 'хрень')], max_length=100, verbose_name='Жанр')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
            },
        ),
    ]
